apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myra-cert-manager-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "myra-cert-manager-webhook.name" . }}
    chart: {{ include "myra-cert-manager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myra-cert-manager-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "myra-cert-manager-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "myra-cert-manager-webhook.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: HOOK_GROUP_NAME
              value: {{ .Values.groupName | quote }}
            - name: MYRA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.myra.apiKeySecretName }}
                  key: api-key
            - name: MYRA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.myra.apiKeySecretName }}
                  key: api-secret
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "myra-cert-manager-webhook.servingCertificate" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
