apiVersion: v1
appVersion: "latest"
description: Helm chart for the Myra cert-manager ACME DNS01 webhook solver
name: cert-manager-webhook-myra
version: 0.1.0
home: https://github.com/KvalitetsIT
icon: https://raw.githubusercontent.com/KvalitetsIT/.github/refs/heads/main/assets/favicon.png
sources:
  - https://github.com/KvalitetsIT/cert-manager-webhook-myra
  - https://github.com/KvalitetsIT/cert-manager-webhook-myra/tree/main/deploy/cert-manager-webhook-myra
maintainers:
  - name: KvalitetsIT
    email: kithosting@kvalitetsit.dk
    url: https://github.com/KvalitetsIT/helm-repo